config/routes.rb
Rails.application.routes.draw do
  get  'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get  'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: %i[index show destroy]
  resource  :password, only: %i[edit update]
  resources :quotes do
    resources :line_item_dates, except: %i[index show] do
      resources :line_items, except: %i[index show]
    end
  end

  namespace :identity do
    resource :email,              only: %i[edit update]
    resource :email_verification, only: %i[show create]
    resource :password_reset,     only: %i[new edit create update]
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
  root to: 'pages#home'
  # root to: 'home#index'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/quote.rb
# frozen_string_literal: true

# Represents a quote in the application.
class Quote < ApplicationRecord
  has_many :line_item_dates, dependent: :destroy
  has_many :line_items, through: :line_item_dates
  belongs_to :company

  validates :name, presence: true
  scope :ordered, -> { order(id: :desc) }
  broadcasts_to ->(quote) { [quote.company, 'quotes'] }, inserts_by: :prepend

  def total_price
    line_items.sum(&:total_price)
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[show edit update destroy]

  def index
    @quotes = current_company.quotes.ordered
  end

  def show
    @line_item_dates = @quote.line_item_dates.includes(:line_items).ordered
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = current_company.quotes.build(quote_params)

    if @quote.save
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: 'Quote was successfully created.' }
        format.turbo_stream { flash.now[:notice] = 'Quote was successfully created.' }
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @quote.update(quote_params)
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: 'Quote was successfully updated' }
        format.turbo_stream { flash.now[:notice] = 'Quote was successfully updated' }
      end

    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_path, notice: 'Quote was successfully destroyed' }
      format.turbo_stream { flash.now[:notice] = 'Quote was successfully destroyed' }
    end
  end

  private

  def set_quote
    @quote = current_company.quotes.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:name)
  end
end

app/views/quotes/_empty_state.html.erb
<div class="empty-state">
  <p class="empty-state__text">
    You don't have any quotes yet!
  </p>
  <%= link_to "Add quote", new_quote_path, class: "btn btn--primary" %>
</div>

app/views/quotes/_form.html.erb
<%= form_with model: quote, class:"form__group" do |f| %>
  <%= form_error_notification(quote) %>
  <%= f.label :name, "Name", class: "visually-hidden" %>
  <%= f.text_field :name, autofocus: true, class: "form__input" %>
  <%= link_to "Cancel", quotes_path, class: "btn btn_light" %>
  <% if  f.object.new_record? %>
    <%= f.submit "Create Quote", class: "btn btn--secondary"  %>
  <% else %>
    <%= f.submit "Update quote", class: "btn btn--secondary"  %>
  <% end %>
<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag quote do %>
  <div class="quote">
    <%= link_to quote.name, quote_path(quote), data: {turbo_frame: "_top" } %>
    <div class="quote__actions">
      <%= button_to "Delete" , quote_path(quote), method: :delete, class: "btn btn--light" , form: {data:
          {turbo_frame: "_top" }} %>
      <%= link_to "Edit" , edit_quote_path(quote), class: "btn btn--light" %>
    </div>
  </div>
<% end %>

app/views/quotes/_total.html.erb
<footer class="quote-total">
  <div class="quote-total__inner container">
    <div>Total:</div>
    <div><%= number_to_currency quote.total_price %></div>
  </div>
</footer>

app/views/quotes/create.turbo_stream.erb
<%= turbo_stream.prepend "quotes", @quote %>
<%= turbo_stream.update Quote.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove @quote  %>
<%= render_turbo_stream_flash_messages %>
<% unless current_company.quotes.exists? %>
  <%= turbo_stream.update Quote.new do %>
    <%= render "quotes/empty_state" %>
  <%end %>
<% end %>

app/views/quotes/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quote"), quote_path(@quote) %>
  <div class="header">
    <h1>Edit quote</h1>
  </div>
  <%= turbo_frame_tag @quote do %>
    <%= render "form", quote: @quote %>
  <% end %>
</main>

app/views/quotes/index.html.erb
<main class="container">
  <%= turbo_frame_tag "first_turbo_frame" do %>
    <div class="header">
      <h1>Quotes</h1>
      <%= link_to "New Quote", 
        new_quote_path, 
        class: "btn btn--primary", 
        data: { turbo_frame: dom_id(Quote.new) }%>
    </div>
  <% end %>
  <%= turbo_frame_tag Quote.new do %>
    <% if @quotes.none? %>
      <%= render "quotes/empty_state" %>
    <% end %>
  <% end %>
  <%= turbo_stream_from current_company, "quotes" %>
  <%= turbo_frame_tag "quotes" do %>
    <%= render @quotes%>
  <% end %>
</main>

app/views/quotes/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
  <div class="header">
    <h1>New quote</h1>
  </div>
  <%= turbo_frame_tag @quote do %>
    <%= render "form", quote: @quote %>
  <% end %>
</main>

app/views/quotes/show.html.erb
<main class="container mb-xxxxl">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
  <div class="header">
    <h1>
      <%= @quote.name %>
    </h1>
    <%= link_to "New date",
                new_quote_line_item_date_path(@quote),
                data: { turbo_frame: dom_id(LineItemDate.new) },
                class: "btn btn--primary" %>
  </div>
  <%= turbo_frame_tag LineItemDate.new %>
  <%= turbo_frame_tag "line_item_dates" do %>
    <%= render @line_item_dates, quote: @quote %>
  <% end %>
</main>
<%= turbo_frame_tag  dom_id(@quote, :total) do%>
  <%= render "quotes/total", quote: @quote %>
<% end %>

app/views/quotes/update.turbo_stream.erb
<%= turbo_stream.replace @quote %>
<%= render_turbo_stream_flash_messages %>